name: CanecciMenu
version: '1.0.0-SNAPSHOT'
main: org.example.com.canecciMenu.Main
api-version: '1.21'
authors: [ TittoFresh ]
description: A custom menu with custom items
permissions:
  caneccimenu.command:
    description: a permission to use caneccimenu command
    default: false
commands:
  caneccimenu: